Repository civicrm/civicrm-packages, pull requests merged in 2018-11, with the labels that each got.

#229 Php 7.2 fix notice on countable
  HTML/QuickForm/advmultiselect.php
Labels: master

#230 dev/core#508 Fix misrepresentation of utf characters on export & other screens using hierSelect
  HTML/QuickForm/hierselect.php
Labels: 5.8

#232 Fix PHP7.2 warning when re-generating schema files
  PHP/Beautifier.php
Labels: master, merge-on-pass

#231 5.8 to master
  HTML/QuickForm/hierselect.php
Labels: master

#228 Fix continue / break warning under PHP 7.3
  DB/DataObject.php
Labels: master

#224 Upgrade to Quickform 3.2.16
  HTML/QuickForm.php
  HTML/QuickForm/Renderer.php
  HTML/QuickForm/Renderer/Array.php
  HTML/QuickForm/Renderer/ArraySmarty.php
  HTML/QuickForm/Renderer/Default.php
  HTML/QuickForm/Renderer/ITDynamic.php
  HTML/QuickForm/Renderer/ITStatic.php
  HTML/QuickForm/Renderer/Object.php
  HTML/QuickForm/Renderer/ObjectFlexy.php
  HTML/QuickForm/Renderer/QuickHtml.php
  HTML/QuickForm/Rule.php
  HTML/QuickForm/Rule/Callback.php
  HTML/QuickForm/Rule/Compare.php
  HTML/QuickForm/Rule/Email.php
  HTML/QuickForm/Rule/Range.php
  HTML/QuickForm/Rule/Regex.php
  HTML/QuickForm/Rule/Required.php
  HTML/QuickForm/RuleRegistry.php
  HTML/QuickForm/advcheckbox.php
  HTML/QuickForm/autocomplete.php
  HTML/QuickForm/button.php
  HTML/QuickForm/checkbox.php
  HTML/QuickForm/date.php
  HTML/QuickForm/element.php
  HTML/QuickForm/file.php
  HTML/QuickForm/group.php
  HTML/QuickForm/header.php
  HTML/QuickForm/hidden.php
  HTML/QuickForm/hiddenselect.php
  HTML/QuickForm/html.php
  HTML/QuickForm/image.php
  HTML/QuickForm/input.php
  HTML/QuickForm/link.php
  HTML/QuickForm/password.php
  HTML/QuickForm/radio.php
  HTML/QuickForm/reset.php
  HTML/QuickForm/select.php
  HTML/QuickForm/static.php
  HTML/QuickForm/submit.php
  HTML/QuickForm/text.php
  HTML/QuickForm/textarea.php
  HTML/QuickForm/utils.php
  HTML/QuickForm/xbutton.php
  VERSIONS.php
Labels: master
