Repository civicrm/civicrm-packages, pull requests merged in 2019-12, with the labels that each got.

#271 dev/core#1469 Mitigate for users that are running ICU 4.4 as the cons…
  HTML/QuickForm/Rule/Email.php
Labels: 5.21

#272 Remove Net_UserAgent_Detect package
  Net/UserAgent/Detect.php
  Net/UserAgent/Detect/APC.php
  VERSIONS.php
  remote-list.pear.php.net
Labels: master

#273 5.21
  HTML/QuickForm/Rule/Email.php
Labels: master

#275 dev/core#395 Define error messages for deadlock.
  DB.php
  DB/mysql.php
  DB/mysqli.php
Labels: master

#279 Remove PEAR package Structures_Graph as there appears to be no use fo…
  Structures/Graph.php
  Structures/Graph/Manipulator/AcyclicTest.php
  Structures/Graph/Manipulator/TopologicalSorter.php
  Structures/Graph/Node.php
  VERSIONS.php
Labels: master, merge-on-pass
