Repository civicrm/civicrm-packages, pull requests merged in 2019-06, with the labels that each got.

#254 Get LegacySimpleCacheTest complient with phpunit6+
  Cache/IntegrationTests/LegacySimpleCacheTest.php
Labels: master, merge-on-pass

#255 Cache/IntegrationTests - Remove. This can be replaced by composer dependency
  Cache/IntegrationTests/LICENSE
  Cache/IntegrationTests/LegacySimpleCacheTest.php
  Cache/IntegrationTests/README.md
Labels: 5.15, merge-on-pass

#256 5.15
  Cache/IntegrationTests/LICENSE
  Cache/IntegrationTests/LegacySimpleCacheTest.php
  Cache/IntegrationTests/README.md
Labels: master
