Repository civicrm/civicrm-packages, pull requests merged in 2022-01, with the labels that each got.

#338 dev/drupal#169 - Fix namespacing in kcfinder
  kcfinder/core/class/browser.php
  kcfinder/core/class/uploader.php
Labels: merge-on-pass, 5.46

#339 Merge 5.46 to master
  kcfinder/core/class/browser.php
  kcfinder/core/class/uploader.php
Labels: master, merge-on-pass

#340 Backport of 338
  kcfinder/core/class/browser.php
  kcfinder/core/class/uploader.php
Labels: 5.45
