Repository civicrm/civicrm-packages, pull requests merged in 2022-10, with the labels that each got.

#350 [REF][PHP8.1] Fix Notice errors on php8.1 when running IDS
  IDS/Event.php
Labels: Merge Ready, 5.55

#351 5.55
  IDS/Event.php
Labels: master

#352 [REF][PHP8.1] Fix Notice errors on php8.1 when running IDS
  IDS/Event.php
Labels: merge-on-pass, 5.54

#353 DB_DataObject - Fix pervasive warnings on PHP 8.2
  DB/DataObject.php
Labels: master, merge-on-pass
