Repository civicrm/civicrm-packages, pull requests merged in 2024-05, with the labels that each got.

#397 Fix setTemplateDir to actually work
  Smarty/Smarty.class.php
Labels: 5.74

#402 5.74 to master
  Smarty/Smarty.class.php
Labels: master

#398 Backport addPluginsDir to Smarty2
  Smarty/Smarty.class.php
Labels: Merge Ready, 5.74

#401 Extract our code to override addPluginsDir
  smarty5/Smarty.php
Labels: Merge Ready, 5.74

#403 5.74 to master
  Smarty/Smarty.class.php
  smarty5/Smarty.php
Labels: master

#399 Add getVersion function
  smarty5/Smarty.php
Labels: 5.74

#405 Composer update on Smarty4-5
  smarty4/composer.lock
  smarty4/vendor/composer/installed.json
  smarty4/vendor/composer/installed.php
  smarty4/vendor/smarty/smarty/CHANGELOG.md
  smarty4/vendor/smarty/smarty/docs/designers/language-builtin-functions/language-function-section.md
  smarty4/vendor/smarty/smarty/libs/Smarty.class.php
  smarty4/vendor/smarty/smarty/libs/sysplugins/smarty_internal_compile_extends.php
  smarty4/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatecompilerbase.php
  smarty5/composer.lock
  smarty5/vendor/composer/installed.json
  smarty5/vendor/composer/installed.php
  smarty5/vendor/smarty/smarty/CHANGELOG.md
  smarty5/vendor/smarty/smarty/docs/designers/language-builtin-functions/language-function-config-load.md
  smarty5/vendor/smarty/smarty/docs/getting-started.md
  smarty5/vendor/smarty/smarty/libs/Smarty.class.php
  smarty5/vendor/smarty/smarty/src/Compile/Tag/ConfigLoad.php
  smarty5/vendor/smarty/smarty/src/Compile/Tag/ExtendsTag.php
  smarty5/vendor/smarty/smarty/src/Compiler/Template.php
  smarty5/vendor/smarty/smarty/src/Smarty.php
Labels: 5.74

#406 Port Extends patch to smarty3
  smarty3/vendor/smarty/smarty/libs/sysplugins/smarty_internal_compile_extends.php
  smarty3/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatecompilerbase.php
Labels: master

#407 5.74 to master
  smarty4/composer.lock
  smarty4/vendor/composer/installed.json
  smarty4/vendor/composer/installed.php
  smarty4/vendor/smarty/smarty/CHANGELOG.md
  smarty4/vendor/smarty/smarty/docs/designers/language-builtin-functions/language-function-section.md
  smarty4/vendor/smarty/smarty/libs/Smarty.class.php
  smarty4/vendor/smarty/smarty/libs/sysplugins/smarty_internal_compile_extends.php
  smarty4/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatecompilerbase.php
  smarty5/Smarty.php
  smarty5/composer.lock
  smarty5/vendor/composer/installed.json
  smarty5/vendor/composer/installed.php
  smarty5/vendor/smarty/smarty/CHANGELOG.md
  smarty5/vendor/smarty/smarty/docs/designers/language-builtin-functions/language-function-config-load.md
  smarty5/vendor/smarty/smarty/docs/getting-started.md
  smarty5/vendor/smarty/smarty/libs/Smarty.class.php
  smarty5/vendor/smarty/smarty/src/Compile/Tag/ConfigLoad.php
  smarty5/vendor/smarty/smarty/src/Compile/Tag/ExtendsTag.php
  smarty5/vendor/smarty/smarty/src/Compiler/Template.php
  smarty5/vendor/smarty/smarty/src/Smarty.php
Labels: master
