Repository civicrm/civicrm-packages, pull requests merged in 2025-02, with the labels that each got.

#417 Fix php8.x support
  Date/Span.php
Labels: 5.82

#418 5.82
  Date/Span.php
Labels: master

#419 PHP compatibility Remove usage of curly braces
  PHP/Beautifier/Filter/Pear.filter.php
Labels: 6.0

#421 Merge 6.0 to master
  HTML/Template/IT.php
  HTML/Template/ITX.php
  PHP/Beautifier/Filter/Pear.filter.php
  Validate.php
Labels: master
